apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-.env: secret/data/k8s/prod/flask-app
        vault.hashicorp.com/agent-inject-template-.env: |
          {{- with secret "secret/data/k8s/prod/flask-app" -}}
          {{- range $key, $value := .Data.data }}
          {{ $key }}: {{ $value }}
          {{- end }}
          {{ end -}}
        vault.hashicorp.com/auth-path: auth/kubernetes-prod
        vault.hashicorp.com/role: prod
        vault.hashicorp.com/secret-volume-path-.env: /env
      labels:
        app: flask-app
    spec:
      serviceAccount: vault-auth
      serviceAccountName: vault-auth
      containers:
      - image: asilbek5999/python-flask-app:latest
        name: flask-app
        resources: {}
status: {}
